# This is a basic workflow to perform a CxSAST Scan and get a redacted report artifact

name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Perform a Checkmarx CxSAST Scan and have a PDF report generated. This report will be redacted.
      - name: Checkmarx Action
        uses: checkmarx-ts/checkmarx-github-action@v1.0.3
        with:
          cxVersion: 2020.4.12
          cxServer: https://sekots92.dev.checkmarx-ts.com
          cxUsername: checkmarx
          cxPassword: ${{ secrets.CX_PASSWORD }}
          cxReportPDF: dvna_cxsast_scan_${{ GITHUB_SHA }}.pdf
          cxTeam: \CxServer

      # Ensure Java is available. The report redaction tool depends on it.
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      
      - name: Download Report Redaction Tool
        run: | 
          wget https://github.com/checkmarx-ts/CxUtils/raw/cxsast-report-redaction/cxsast-report-redaction/artifacts/cxsast-pdf-report-redactor-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          chmod 755 cxsast-pdf-report-redactor-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          
      - name: Redact CxSAST Report
        run: |
          java -jar cxsast-pdf-report-redactor-0.0.1-SNAPSHOT-jar-with-dependencies.jar "${{ github.workspace }}/cxcli/Checkmarx/Reports/dvna_cxsast_scan_${{ GITHUB_SHA }}.pdff" "${{ github.workspace }}/cxcli/Checkmarx/Reports/dvna_cxsast_scan_REDACTED_${{ GITHUB_SHA }}.pdf"
          # Un comment the line below to delete the original report if desired
          # rm ${{ github.workspace }}/cxcli/Checkmarx/Reports/dvna_cxsast_scan_REDACTED_${{ GITHUB_SHA }}.pdf
        
      - name: Upload CxSAST Reports
        uses: actions/upload-artifact@v2
        with: 
          name: cxsast-reports
          path: ${{ github.workspace }}/cxcli/Checkmarx/Reports
          
